### ISSUE TITLE
Missing information on Palace Diplocaulus

### ISSUE THREAD

**Issue by corgidogs** [IAmLokken/DeepDungeonOverlay#1]
Hey there,

First of all, great plugin! It's super nice not having to constantly look over on a second monitor or to dig up the handbook each time i'm going in to play solo.

While doing a 51-100 run, I noticed the information for the Palace Diplocaulus was missing. I know everything on this floor is trivial so the information isn't needed but still wanting to bring this up. Attached below is a screenshot of what it looks like.

![image](https://user-images.githubusercontent.com/91865433/136635861-c239d880-3195-4cc6-8096-4314f2071460.png)

**Comment by IAmLokken** [comment]
Hi corgidogs!

Thanks a bunch for the help.  I have updated this entry:
![image](https://user-images.githubusercontent.com/46271810/136643959-78cae97c-ad5e-4b2c-8db4-2f3b8055dd9a.png)

To see this reflected you can re-start ACT or press the 'Reload overlay' button at the bottom of the General tab for the overlay.  Make sure not to do either while in a deep dungeon.

Lokken
