### ISSUE TITLE
Heavenly Yak can be slowed (HOH)

### ISSUE THREAD

**Issue by LichFrosty** [IAmLokken/DeepDungeonOverlay#7]
Beastiery info stated it couldn't be slowed, picture below shows it with the slow debuff (debuff is in front of the yak)
![ffxiv_12112021_162845_247](https://user-images.githubusercontent.com/94187341/141496444-1a169dc9-791f-489c-8d53-015ca4666688.png)

**Comment by IAmLokken** [comment]
Hi LichFrosty

Thanks for letting me know!  This has been fixed and pushed live.

Lokken
